name: Playwright Test After Cloudflare Deploy

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      base-url:
        description: URL to test
        required: false
        default: https://develop.kp-author-site.pages.dev
        type: string

jobs:
  test:
    name: Run Playwright Tests
    if: ${{ (github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && (((github.event.deployment.ref == 'develop' || github.event.deployment.ref == 'refs/heads/develop') && startsWith(github.event.deployment_status.environment_url, 'https://develop.kp-author-site.pages.dev')) || ((github.event.deployment.ref == 'main' || github.event.deployment.ref == 'refs/heads/main') && (startsWith(github.event.deployment_status.environment_url, 'https://kp-author-site.pages.dev') || startsWith(github.event.deployment_status.environment_url, 'https://kerynpowellauthor.nz') || startsWith(github.event.deployment_status.environment_url, 'https://www.kerynpowellauthor.nz'))))) || github.event_name == 'workflow_dispatch' }}
    uses: imclarenpow/playwright-kp-author/.github/workflows/test-action.yml@main
    with:
      test-script: test:smoke
      base-url: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.environment_url || inputs.base-url }}
